#+TITLE: ArtS - Knowledge Base
#+AUTHOR: Artem Smaznov
#+DESCRIPTION: Artem's site on linux
#+STARTUP: overview
#+OPTIONS: num:nil ^:{}
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="gruvbox.css"/>
#+INCLUDE: header.org

* ssh
** Extending Screens
You can add another computer's monitor to your host's screen and control it using your keyboard and mouse as if it was an extra monitor. It can come in handy when working on 2 computers as you can control both with the same of keyboard and mouse.

- =user@host:port= specify the host to add to your screen.
- =-east= select which direction from your current monitors the new one will be added
#+begin_src shell
ssh -YC user@host:port x2x -east -to :0.0
#+end_src

* git
** Bare Repositories
Turning off untracked files for git status for bare repositories.
#+begin_src shell
git config status.showUntrackedFiles off
#+end_src

* sort
Print out unique lines of the file in descending order.
#+begin_src shell
sort -u file
#+end_src

* awk
Print the first column (separated by =:=) from =/etc/passwd=.
#+begin_src shell
awk -F: '{print $1}' /etc/passwd
#+end_src

Print the first column (separated by =:=) from =/etc/passwd= where the 3rd column is
=1000=.
#+begin_src shell
awk -F: '$3=="1000" {print $1}' /etc/passwd
#+end_src

* date
Convert dates between different formats.

The example converts it to the Unix Epoch format that can be used to compare
different dates.
#+begin_src shell
date -d "12:30" +%s
#+end_src

#+RESULTS:
: 1641558600

* cmatrix
Send any output (like cmatrix) to the TTY screen.

User needs to be logged in on the TTY and not have a Graphical environment
running. Best done over SSH on servers.

Might need =sudo= to be executed.
#+begin_src shell
cmatrix > /dev/tty2
#+end_src

